### ISSUE TITLE
Metabo thicknesser: risk assessment and training documentation

### ISSUE THREAD

**Issue by mdales** [Makespace/WoodworkingWorkshop#18]
Before the new Metabo thicknesser can go into general use I need to complete a risk assessment and write up training. Currently I'm block on the former waiting for an example from Jonathan, after which I'll put together a training plan and run it by @gndurant.

**Comment by sensor111** [comment]
is it thicknesser or plane/ticknesser?

**Comment by camwoolf** [comment]
Shoot I though I had emailed you the Risk Assessment and H&S ! Will double check now.
