### ISSUE TITLE
24V PSU Required for testing Masso CNC Router Controller

### ISSUE THREAD

**Issue by mdales** [Makespace/WoodworkingWorkshop#6]
The current controller is still causing issues, with several people (me, Phil, and Allen) all reporting poor behaviour with it. We have a Masso Controller unit, but that needs testing. To do that, we need a new PSU for it (the old one is on the DM500 in the CNC Router at the moment). 

Adrian is doing this.

**Comment by avdheever** [comment]
Has been ordered - will arrive Friday 2019/05/03

**Comment by mdales** [comment]
This is now in the office with the CNC kit
